services:
  persistencia:
    image: mysql:8.0
    container_name: persistencia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: diplomado
      MYSQL_DATABASE: persistencia
      MYSQL_USER: diplomado
      MYSQL_PASSWORD: diplomado
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - datosdb:/var/lib/mysql
    networks:
      - red_interna
    ports:
      - "3306:3306"

  app:
    build: ./app
    container_name: app
    restart: always
    depends_on:
      - persistencia
    networks:
      - red_interna
    volumes:
      - archivos_data:/app/archivos
      - firmas_data:/app/firmas
    env_file:
      - app/oauth.env

  firewall:
    build: ./firewall
    container_name: firewall
    restart: always
    depends_on:
      - app
    networks:
      - red_interna
    ports:
      - "443:443"
    cap_add:
      - NET_ADMIN
    privileged: true

volumes:
  datosdb:
  archivos_data:
  firmas_data:

networks:
  red_interna:
    driver: bridge
